### ISSUE TITLE
Modal - Hintergrund scrollt mit

### ISSUE THREAD

**Issue by skerbis** [gupi/addon_viewer#1]
Wenn man im Modal zur Anzeige des Quellendes scrollt, scrollt der Hintergrund (also die restliche REDAXO-Oberfläche mit). Modals dieser Art sind eher sinnvoll bei kurzen Inhalten. Alternativ sollte das Modal auf eine Höhe fixiert werden und der darin enthaltene Content scrollbar sein.

**Comment by gupi** [comment]
Kann ich auf meinem Mac weder mit Safari noch mit Firefox nachvollziehen. Allerdings ist dein Vorschlag mit der fixen höhe und des scrollbaren Inhalts ein guter und sinnvoller Ansatz für einen Update. Wird im nächsten Release übernommen.

**Comment by skerbis** [comment]
Wenn du dan das Ende des Modals kommst (vor allem wenn es höher ist als der Viewport) fängt der Hintergrund zu scrollen an. Getestet in FF, Safari, Chrome
